import {renderMonitoring} from './monitoring.mjs';
import {renderReaderPanels} from './reader-panels.mjs';

const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function renderLayout({content,monitoring,site,categories,articles}) {
  const option=(value,label)=>`<option value="${escape(value)}">${escape(label)}</option>`;
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escape(site.description)}"><title>${escape(site.homeTitle)}</title><link rel="icon" href="logo.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script src="client.js" defer></script></head>
<body><a class="skip" href="#news">跳到资讯</a><div class="topline"><div><span>独立行业资讯 · 中文摘要 / 官方原文</span><span>马来西亚 UTC+8</span></div></div><header><div class="header-inner"><a class="brand" href="./"><img src="logo.svg" width="40" height="40" alt=""><span>Malaysia Water Watch<small>马来西亚水利观察</small></span></a><nav aria-label="主导航"><a href="#news">最新资讯</a><a href="#weather">天气与预警</a><a href="#official">官方来源</a><a href="#about">关于本站</a></nav><a class="github-link" href="${escape(site.github)}" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></header>
<main><section class="editorial-intro"><div><p class="eyebrow">WATER · FLOOD · MALAYSIA</p><h1>关注水利变化，读懂工程动态。</h1><p>防洪、水文、工程、政策与招标，一处查阅。</p></div><div class="edition"><span>本期核查</span><strong>${escape(content.reviewedAt)}</strong><small>每天 08:30 核查 · 以官方最新公告为准</small></div></section>
<div class="news-layout"><section id="news"><div class="section-heading"><h2>最新资讯<span class="heading-rule"></span></h2><span id="count" role="status" aria-live="polite">${content.articles.length} 条</span></div><form class="filters" role="search" onsubmit="return false"><label class="search-label">搜索资讯<input id="query" type="search" placeholder="搜索项目、机构或地区" autocomplete="off"></label><label>分类<select id="category">${option('','全部分类')}${categories.map(c=>option(c.key,c.label)).join('')}</select></label><label>来源<select id="source">${option('','全部来源')}${content.sources.filter(s=>content.articles.some(a=>a.source===s.id)).map(s=>option(s.id,s.name)).join('')}</select></label><button id="reset" type="button" title="清除全部筛选">重置</button></form><noscript><p>未启用 JavaScript，仍可阅读全部资讯与天气；搜索和筛选暂不可用。</p></noscript><div id="stories">${articles}</div><p id="empty" class="empty" ${content.articles.length ? 'hidden' : ''}>没有符合条件的收录。这不代表没有事件或官方公告，请查阅官方来源。</p></section><aside aria-label="天气、气象公告与水质">${renderReaderPanels(monitoring)}<div class="sidebar-note"><strong>信息使用说明</strong><p>天气与预警是采集时的记录，页面不会实时刷新。新闻保留原始发布日期，较早资料继续作为参考。</p><a href="#official">查阅官方来源与更新时间 ↓</a></div></aside></div>
${renderMonitoring(content,monitoring)}
<section id="about" class="about"><div><p class="eyebrow">ABOUT THE WATCH</p><h2>中文阅读，官方依据。</h2></div><div><p>Malaysia Water Watch 是独立的水利与防洪行业资讯索引。我们阅读官方原文，整理中文摘要，保留原始日期、工程阶段与来源。原文版权归各来源。</p><p>每天马来西亚时间 08:30 由 Codex 核查并提交 GitHub。运行任务的电脑、Codex 应用和网络须可用。候选链接经过阅读核对后才收录，不代表政府公告或实时预警。</p><p>本站无广告、追踪代码或登录表单。使用与隐私说明见页脚；天气及资讯请同时核对官方原文。</p></div></section></main><footer><span>Malaysia Water Watch · 马来西亚水利观察</span><span>资料核查 ${escape(content.reviewedAt)} · <a href="${escape(site.github)}" target="_blank" rel="noopener noreferrer">代码与内容 ↗</a> · <a href="terms.html">使用规则</a> · <a href="privacy.html">隐私说明</a></span></footer></body></html>`;
}
